
INSERT INTO public.site_content (section, key, value) VALUES
('about', 'profile', '{"name": "Bishesh Nakarmi", "title": "Frontend Developer", "location": "Kathmandu, Nepal", "description": "Passionate frontend developer with 3+ years of experience building modern web applications using React, JavaScript, and cutting-edge technologies. Currently working at NEPA Works."}'::jsonb),
('about', 'social_links', '[{"platform": "GitHub", "url": "https://github.com/Bisesh-n", "icon": "github"}, {"platform": "LinkedIn", "url": "https://www.linkedin.com/in/bisesh-nakarmi/", "icon": "linkedin"}]'::jsonb),
('experience', 'items', '[{"title": "Developer", "company": "NEPA Works", "period": "Current", "description": "Working on modern web applications and contributing to full-stack development projects."}, {"title": "Frontend Developer", "company": "VoxCrow Pvt. Ltd.", "period": "Apr 2020 – Jun 2023", "description": "Built and maintained responsive web applications using React, JavaScript, and modern frontend tooling."}, {"title": "SEO Intern", "company": "BlendWit International", "period": "Sep 2019 – Jan 2020", "description": "Assisted in SEO strategy, keyword research, and on-page optimization for client websites."}]'::jsonb),
('education', 'items', '[{"title": "MSc. IT", "company": "Islington College", "period": "2023 – Present", "description": "Master of Science in Information Technology."}, {"title": "BSc. CSIT", "company": "Academia International College", "period": "2016 – 2021", "description": "Bachelor of Science in Computer Science and Information Technology."}, {"title": "+2 Science", "company": "Kathmandu Model Secondary School", "period": "2014 – 2016", "description": "Higher secondary education in Science."}]'::jsonb),
('skills', 'technical', '["React", "JavaScript", "TypeScript", "Python", "PHP", "HTML5", "CSS3", "Tailwind CSS", "Bootstrap", "jQuery", "Node.js", "MongoDB", "PostgreSQL", "MySQL", "Git", "GitHub", "REST APIs", "Firebase", "Redux", "Next.js"]'::jsonb),
('skills', 'soft', '["Problem Solving", "Team Collaboration", "Communication", "Time Management", "Adaptability", "Leadership"]'::jsonb)
ON CONFLICT DO NOTHING;
